name: Uber_Deli
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.11.1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

fonts:
  - family: HachiMaruPop-Regular
    fonts:
      - asset: fonts/HachiMaruPop-Regular.ttf
